name: Node CI

on: [push]

jobs:

  container-job:

    runs-on: ubuntu-latest

    container: node:14.15-buster

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm ci

      - name: Connect to PostgreSQL
        # Runs a script that creates a PostgreSQL client and creates a database
        run: node pgclient.js
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432

      - name: Build and test
        run: |
          npm run build --if-present
          npm test
        env:
          CI: true
          AUTH0_TEST_TOKEN: ${{ secrets.AUTH0_TEST_TOKEN }}
